### ISSUE TITLE
Research Gyroscopic/Inertia Sensors

### ISSUE THREAD

**Issue by TonyP820** [UAA-Robo/CoffeeBot#11]
### Description
Research various gyroscopic/inertia controllers for use in the CoffeeBot. Return with **3 or more solutions** of various quality (unlimited budget, reasonable budget, dumpster diving budget). The 3+ solutions is both for team consideration and investor consideration during our pitch. 

You will own whichever solution is ultimately decided upon and will be expected to become the "resident expert" upon acquisition and arrival. 

### DOD
This task its considered done when 3+ solutions are thoroughly documented in the [CoffeBot Log](https://docs.google.com/document/d/1G20I_BOJlpeXFwSVG0fJs26bjP2y9NoJx31wkVBgNbQ/edit?usp=sharing).

**Comment by schromya** [comment]
Ramiro added added to CoffeeBot log under "Programming" ->"Sensor and Motor Decisions"  ->"2023-02-13 Initial Research" ->  "Gyroscopic/Inertia Sensors"
