### ISSUE TITLE
Research Limit Switches

### ISSUE THREAD

**Issue by TonyP820** [UAA-Robo/CoffeeBot#12]
### Description
Research limit switches, select 3 viable solutions with the following budget considerations. (unlimited budget, reasonable budget, dumpster diving budget). Multiple solutions are both for team consideration and investor consideration during our pitch. 

You will own whichever solution is ultimately decided upon and will be expected to become the "resident expert" upon acquisition and arrival. 

### DOD
This task its considered done when 3+ solutions are thoroughly documented in the [CoffeBot Log](https://docs.google.com/document/d/1G20I_BOJlpeXFwSVG0fJs26bjP2y9NoJx31wkVBgNbQ/edit?usp=sharing).

**Comment by schromya** [comment]
Info added to CoffeeBot log under "Programming" ->"Sensor and Motor Decisions"  ->"2023-02-13 Initial Research" ->  "Limit Switches"
