### ISSUE TITLE
Research Vision Cameras

### ISSUE THREAD

**Issue by TonyP820** [UAA-Robo/CoffeeBot#13]
### Description
Research various vision cameras; select 3 viable solutions with the following budget considerations. (unlimited budget, reasonable budget, dumpster diving budget).Multiple solutions are both for team consideration and investor consideration during our pitch.

You will own whichever solution is ultimately decided upon and will be expected to become the "resident expert" upon acquisition and arrival. 

### DOD
This task its considered done when 3+ solutions are thoroughly documented in the [CoffeBot Log](https://docs.google.com/document/d/1G20I_BOJlpeXFwSVG0fJs26bjP2y9NoJx31wkVBgNbQ/edit?usp=sharing).

**Comment by patpragman** [comment]
**Solution 1:**  I just bought a couple of these [cameras](https://www.amazon.com/gp/product/B084ZJFNKN/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1)

They're cheap and they work pretty well.  I used them on the BroPro (ask Jaren).  I have to prepare for a presentation but I can provide more camera stuff later.

**Comment by patpragman** [comment]
@TonyP820 - do we have a selection for this, or are we still just kind of unsure?  I know the scope of the miniature changed a bit.

**Comment by TonyP820** [comment]
@patpragman No, we don't have a selection as of yet; we aren't using any cameras for the scaled-down version.
