### ISSUE TITLE
Research PDP system

### ISSUE THREAD

**Issue by schromya** [UAA-Robo/CoffeeBot#15]
### Description
Research PDP (Power Distribution Panel). This includes making sure it can interface (with I2C) with motors/encoders and Raspberry Pie. Select 3 viable solutions with the following budget considerations:unlimited budget, reasonable budget, dumpster diving budget).Multiple solutions are both for team consideration and investor consideration during our pitch.

You will own whichever solution is ultimately decided upon and will be expected to become the "resident expert" upon acquisition and arrival.

### DOD
This task its considered done when 3+ solutions are thoroughly documented in the [CoffeBot Log](https://docs.google.com/document/d/1G20I_BOJlpeXFwSVG0fJs26bjP2y9NoJx31wkVBgNbQ/edit?usp=sharing) with price, pros/cons, and link to buy.

**Comment by eleonora-sc** [comment]
Information added under "Sensor and Motor Decisions" -> "PDP system"
