### ISSUE TITLE
Claw CAD

### ISSUE THREAD

**Issue by micahkayle** [UAA-Robo/CoffeeBot#20]

**Comment by Dawson-Packer** [comment]
Claw “fingers” CAD basics done, will refine for more detail later
Basic baseplate done
Todo:
- Must investigate motor mounting (remove material from finger cogs to make room for stand-offs?)
    - Redesign baseplate for this use plus ready effector for rotational mount to larger motor for 270 degree spin
- Look at simulating claw grip animation

**Comment by Dawson-Packer** [comment]
Claw CAD expected to have first iteration done by Friday meeting (2/24/23). Much progress made on claw assembly. See CoffeeBot Log for more details.
Todo:
- Place motor in CAD
- Bore hole in pivot plate for swivel motor
- Split drive finger into two fingers

**Comment by Dawson-Packer** [comment]
Fixed Pivot plate dimensions. Removed material from top and base plate to make claw lighter. Detailed fingers. Driving finger has two contact points. Driven finger has one.
Todo:
- Place motor in CAD
- Bore hole in pivot plate for swivel motor
- Look at additional support for motor.

**Comment by Dawson-Packer** [comment]
First actual component 3D-printed yesterday. Will continue to print on Monday. Look at closing this task when full model is functional.

**Comment by Dawson-Packer** [comment]
Interfacing grooves on printed part don’t fit. Must revise (Monday)

**Comment by Dawson-Packer** [comment]
Interface fixed! Everything on schedule now.

**Comment by Dawson-Packer** [comment]
First Iteration done
