### ISSUE TITLE
Experiment with Microcontrollers via Rasp Pie -> Arduino

### ISSUE THREAD

**Issue by TonyP820** [UAA-Robo/CoffeeBot#26]
Experiment with controlling motors using Arduino as a microcontroller (middleman) between the raspberry pie and motors.

**Comment by schromya** [comment]
Got a Arduino to move a server based on Serial Monitor from the Arduino IDE. See `Programing > Servo Control With Arduino > 2023-05-16 Turning servo to position based on Serial Monitor Input` in the CoffeeBot log.
